### ISSUE TITLE
Raise an exception for unsupported language elements

### ISSUE THREAD

**Issue by mrsimpson** [abaplint/transpiler#10]
When transpiling as part of a build, it is essential to know whether the input could be transpiled "properly".

**Comment by larshp** [comment]
as is, an exception should be thrown, https://github.com/abaplint/transpiler/blob/master/packages/transpiler/src/index.ts#L58

but there is also a lot of places that just output "todo"

**Comment by larshp** [comment]
this is done? issue can be closed?

**Comment by mrsimpson** [comment]
Closed by #12
