### ISSUE TITLE
0 objects written to disk

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/transpiler#1024]
Hi, what are the conditions for the Transpiler to write an object to a disk?
I have a class with a local test class. Transpiler gets it into account by saying `9 files added` and still I got the `0 objects written to disk`.

![obraz](https://user-images.githubusercontent.com/9119187/206168647-589bd203-dfc9-444e-802d-b64e7aba65f3.png)

**Comment by larshp** [comment]
try making a public example?

**Comment by Zeatynis** [comment]
I have abaplint errors in this code... That's probably it. Why transpiler didn't say anything? 0o

**Comment by Zeatynis** [comment]
Ok, @larshp, here is the repo. I had to make it private as it contains proprietary code.

**Comment by larshp** [comment]
add `@abaplint/transpiler-cli` as a dependency to `package.json`

**Comment by Zeatynis** [comment]
ofc it worked... I don't know how I missed that... :disappointed:
