### ISSUE TITLE
Built-in: find does not support `len` and `occ` parameters

### ISSUE THREAD

**Issue by mbtools** [abaplint/transpiler#1056]
https://help.sap.com/doc/abapdocu_756_index_htm/7.56/en-US/index.htm?file=abensearch_functions.htm
https://github.com/abaplint/transpiler/blob/main/packages/runtime/src/builtin/find.ts

Observations:
- `len` not supported
- `occ` not supported
- `off` does not work for `regex`

```abap
DATA f TYPE i.
DATA o TYPE i VALUE '-3'.
DO 6 TIMES.
  f = find(
    val = '/test/path/file.xml'
    sub = '/'
    occ = o ).
  WRITE: / o, f.
  o = o + 1.
  IF o = 0.
    o = o + 1.
  ENDIF.
ENDDO.
```

Exp:

```
3-          0
2-          5
1-         10
1           0
2           5
3          10
```

Act:

```
-3 0
-2 0
-1 0
1 0
2 0
3 0
```

**Comment by larshp** [comment]
`occ` implemented

the other stuff will now throw errors if used

**Comment by larshp** [comment]
![image](https://user-images.githubusercontent.com/5888506/212715181-1f9766c7-9923-4e45-94b1-2eac089e4229.png)
