### ISSUE TITLE
Async run()

### ISSUE THREAD

**Issue by mrsimpson** [abaplint/transpiler#11]
Probably easier now than later. 
Proposal: `async` and promise everything

**Comment by larshp** [comment]
hmm, yea now its easier than later

just wondering which parts will be true async

**Comment by mrsimpson** [comment]
at leat `run()`

**Comment by larshp** [comment]
yea

async is only ES draft mode, https://caniuse.com/#feat=async-functions, not really a problem, just need to note it somewhere

**Comment by mrsimpson** [comment]
You care about IE11? 😬 
You could transpile for we using babel and polyfills (which I'd anyway recommend for web)

**Comment by larshp** [comment]
IE11, no

but care about following open standards

if opening the JS compile topic, then another option is to output TypeScript instead of JS, but its more steps

**Comment by larshp** [comment]
updated, 

`  public async runMulti(files: IFile[]): Promise<IOutput> {`

https://github.com/abaplint/transpiler/blob/master/packages/transpiler/src/index.ts#L27

**Comment by mrsimpson** [comment]
When shall we replace `run()` with the implementation of `runMulti`?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by larshp** [comment]
yes, just need the code to be refactored to use runMulti

then delete run, and rename runMulti to run

**Comment by mrsimpson** [comment]
In the current phase, I’d just say: once you’re done, release `0.3.0` wie a Breaking-Note drop the old method. As long as we’re pre 1.0, also npm does not automatically update the minor-version

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by larshp** [comment]
agree

0.3.0 is out earlier today, so perhaps for 0.4.0
