### ISSUE TITLE
Bug in `TRANSLATE`

### ISSUE THREAD

**Issue by mbtools** [abaplint/transpiler#1309]
```abap
DATA s TYPE string.
s = 'A'.
TRANSLATE s USING 'ABBC'.
WRITE s.
```

result: `C`, correct: `B`

A character in text that has already been replaced cannot be replaced again in the same TRANSLATE statement.

https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abaptranslate.htm

**Comment by larshp** [comment]
starting this task now

**Comment by larshp** [comment]
@mbtools try again, 2.7.84 published

**Comment by mbtools** [comment]
👍
