### ISSUE TITLE
LOOP AT - "WHERE" is ignored

### ISSUE THREAD

**Issue by smb** [abaplint/transpiler#142]
`LOOP AT inputtab INTO DATA(string2) WHERE table_line <> string1.`

is transpiled to:

```
    for (let unique3 of inputtab.array()) {
      string1.set(unique3);
```

so the "WHERE" part is ignored here

**Comment by larshp** [comment]
delete internal has some WHERE functionality, perhaps some of it can be reused, https://github.com/abaplint/transpiler/blob/master/packages/runtime/src/statements/delete_internal.ts

**Comment by larshp** [comment]
test case, 

```abap
DATA tab TYPE STANDARD TABLE OF i WITH DEFAULT KEY.
DATA line LIKE LINE OF tab.
DO 5 TIMES.
  APPEND sy-index TO tab.
ENDDO.
LOOP AT tab INTO line WHERE table_line <> 3.
  WRITE / line.
ENDLOOP.
```

**Comment by larshp** [comment]
hmm, need to think about this one a bit more

**Comment by joltdx** [comment]
It's pretty much the reverse of https://github.com/abaplint/abaplint/issues/1370. In theory at least :)

**Comment by larshp** [comment]
I'm starting this

**Comment by larshp** [comment]
this should work now, closing
