### ISSUE TITLE
Half up rounding not done for integer = '45141.58832' (actual: 45141, expected: 45142)

### ISSUE THREAD

**Issue by sandraros** [abaplint/transpiler#1431]
There's a failure with abap2xlsx unit test (see the [log](https://github.com/abap2xlsx/abap2xlsx/actions/runs/8675300991/job/23788592877?pr=1197) corresponding to the pull request https://github.com/abap2xlsx/abap2xlsx/pull/1197).

Probably, it's related to this [code](https://github.com/kjetil-kilhavn/abap2xlsx/blob/47bac2e78d4e416f039c7792127219613306a7a1/src/zcl_excel_common.clas.testclasses.abap#L693-L699):
```abap
* 45141.58832 (2023/08/03 14:07:11) ip_exact = abap_false -> 2023/08/04
    TRY.
        ep_value = zcl_excel_common=>excel_string_to_date( ip_value = '45141.58832'
                                                           ip_exact = abap_false ).
        cl_abap_unit_assert=>assert_equals(
          act   = ep_value
          exp   = '20230804' ).
```
and [zcl_excel_common=>excel_string_to_date](https://github.com/kjetil-kilhavn/abap2xlsx/blob/47bac2e78d4e416f039c7792127219613306a7a1/src/zcl_excel_common.clas.abap#L874-L884):
```abap
  METHOD excel_string_to_date.
    DATA: lv_date_int TYPE i.
    DATA lv_error_text TYPE string.

    CHECK ip_value IS NOT INITIAL AND ip_value CN ' 0'.

    TRY.
        IF ip_exact = abap_false.
          lv_date_int = ip_value.
        ELSE.
          lv_date_int = trunc( ip_value ).
```

The code which should be executed is `lv_date_int = ip_value`, where ip_value = '45141.58832'. I guess that the transpiler calculates `45141`, but it should calculate `45142`.

Thank you.

**Comment by larshp** [comment]
thanks, note its not a required check in abap2xlsx, also feel free to ping me in the PR if it fails

looking into it now

**Comment by sandraros** [comment]
Oh I didn't realize it was optional, no hurry so. Thank you.

**Comment by larshp** [comment]
reproduced, 
![image](https://github.com/abaplint/transpiler/assets/5888506/1aee935c-287f-4e8f-ae04-74102bba7633)

**Comment by larshp** [comment]
@sandraros try again, 2.8.24 published

I've also opened https://github.com/abap2xlsx/abap2xlsx/pull/1207

**Comment by sandraros** [comment]
It's now okay, thank you very much!
