### ISSUE TITLE
Package-json not consistent with the required dependencies

### ISSUE THREAD

**Issue by Sarthak-Kakkar-03** [abaplint/transpiler#1445]
Neither npm install nor npm ci end up downloading all the dependencies appropriately, which leads to the endless cycle of having to test, let it fail and then downloading the needed dependency.
![image](https://github.com/abaplint/transpiler/assets/104781539/5ea55456-49e9-434c-8ec1-b7138a972911)

**Comment by larshp** [comment]
it works, all code runs with continuous integration

**Comment by Sarthak-Kakkar-03** [comment]
In that case, how can I bypass this error/run this code? I am seemingly unable to find concrete documentation for the same. Up till this error, multiple errors kept popping up and I kept updating the libraries for some other error to come up. How do I fix that? Or maybe I am going the wrong way about running the code at all?

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/blob/main/README.md#development

**Comment by larshp** [comment]
also check the github actions, which runs without problems, https://github.com/abaplint/transpiler/tree/main/.github/workflows

**Comment by arcanist123** [comment]
I just checked the installation myself - new folder. git clone, npm
install, npm run test
it works (the installation)

**Comment by larshp** [comment]
thanks, closing
