### ISSUE TITLE
ENHANCEMENT-POINT not implemented - breaks transpilation

### ISSUE THREAD

**Issue by joltdx** [abaplint/transpiler#1464]
ENHANCEMENT-POINT is not implemented and currently breaks transpilation...

```abap
WRITE 'foo'.
ENHANCEMENT-POINT foo SPOTS bar.
WRITE 'bar'.
```
`Error: Statement EnhancementPoint not supported, ENHANCEMENT-POINT foo SPOTS bar.`

![image](https://github.com/user-attachments/assets/01a83c28-36ca-44bd-a599-e469c1139637)

**Comment by joltdx** [comment]
I don't think I can manage implementing the full functional thing, but I can implement something that does nothing, to avoid breaking transpilation?

**Comment by larshp** [comment]
yea, feel free to do something like https://github.com/abaplint/transpiler/blob/main/packages/transpiler/src/statements/log_point.ts

perhaps have it output a ABAP comment with the name of the point and spot
