### ISSUE TITLE
field-symbols with [] not handled properly

### ISSUE THREAD

**Issue by joltdx** [abaplint/transpiler#1476]
Seems the new version does not handle [] for field-symbols properly

`<baz>[] = foo[].` transpiles to `fs_baz_[].set(foo);`, which JavaScript does not approve of

```abap
data foo type standard table of string.
data bar like foo.
data baz like foo.
field-symbols <baz> like baz.

assign baz to <baz>.

append 'arf' to foo.
append 'meh' to foo.
append 'woo' to foo.

"These should be equal:
bar = foo.
bar[] = foo[].
<baz> = foo.
<baz>[] = foo[].
```

![image](https://github.com/user-attachments/assets/d9b68b47-38fe-4be5-ac1a-586c760ab045)

**Comment by larshp** [comment]
@joltdx try again, new version published

**Comment by joltdx** [comment]
Works properly, thank you 🎉
