### ISSUE TITLE
BETWEEN does not care about NOT

### ISSUE THREAD

**Issue by joltdx** [abaplint/transpiler#152]
`IF foo NOT BETWEEN 5 AND 10.`
is transpiled to:
`if (abap.compare.between(foo, constant_5, constant_10)) {`

Adding parantheses helps...
`IF NOT ( foo BETWEEN 5 AND 10 ).`
transpiles to:
`if (!(abap.compare.between(foo, constant_5, constant_10))) {`

**Comment by joltdx** [comment]
Let me see if I can contribute by figuring this one out during the weekend... :)

**Comment by larshp** [comment]
let me know if you like some hints, also feel free to join the abapGit slack https://abapgit-slackinviter.herokuapp.com/, there is an advent of code channel plus abaplint

**Comment by larshp** [comment]
closing
