### ISSUE TITLE
LOOP does not support REFERENCE with inline declarations

### ISSUE THREAD

**Issue by joltdx** [abaplint/transpiler#153]
```
DATA table TYPE STANDARD TABLE OF string.
DATA declared_line TYPE string.

" These works just fine:
LOOP AT table INTO declared_line.
LOOP AT table REFERENCE INTO declared_line.
LOOP AT table INTO DATA(inline_1).

" This one does not:
LOOP AT table REFERENCE INTO DATA(inline_2).
```

Workarounds are plenty.

**Comment by joltdx** [comment]
All options work for READ TABLE. 👍

**Comment by larshp** [comment]
the transpiler currently targets 702 syntax, so the abaplint downport feature is used to "out-line" the inline variables

so this would probably be a fix in the rule https://rules.abaplint.org/downport/

**Comment by larshp** [comment]
scenario above will be fixed via https://github.com/abaplint/abaplint/pull/1591
