### ISSUE TITLE
Class attributes not set properly within methods

### ISSUE THREAD

**Issue by s7oev** [abaplint/transpiler#200]
First of all, I should mention I am running from web - not sure if it is on newest version. If not, may be this problem is fixed - if so, just directly close the issue.

Scenario: I've tried creating a class with a setter and getter. Afer running the class, unfortunately, the result is not correct from the transpiler, but correct from an SAP system.

Code:
```
class car definition.
  public section.
    methods:
      set_wheels importing i_wheels type i,
      get_wheels returning value(result) type i.
  
  private section.
    data:
      wheels type i.
endclass.

class car implementation.
  method set_wheels.
    me->wheels = i_wheels.
  endmethod.

  method get_wheels.
    result = me->wheels.
  endmethod.
endclass.

data mercedes type ref to car.
create object mercedes.
mercedes->set_wheels( 5 ).
write: mercedes->get_wheels( ).
```

ABAP transpiler returns 0. SAP system returns 5. The code is the same with only exception  I ran it in the SAP system with a start-of-selection before the _mercedes_ data definition. Still, even if I add start-of-selection to the transpiler, the result is the same (0).

**Comment by larshp** [comment]
Hi,
There are some problems with code on the top level, try wrapping the code into a FORM,

![image](https://user-images.githubusercontent.com/5888506/102065018-4e504800-3df8-11eb-94ab-b8737d6389ec.png)

**Comment by larshp** [comment]
root cause = https://github.com/abaplint/abaplint/issues/808

**Comment by s7oev** [comment]
Hey Lars,

Thanks for your quick reply. Indeed, the issue is apparently not the actual setting of parameters, as demonstrated in your example.

An even simple work-around I've thought of is to simply use a main method as we would in Java. If we call the same code wrapped in the (static) main method, it's all good:

```
class car definition.
  public section.
    class-methods:
      main.

    methods:
      set_wheels importing i_wheels type i,
      get_wheels returning value(result) type i.
  
  private section.
    data:
      wheels type i.
endclass.

class car implementation.
  method set_wheels.
    me->wheels = i_wheels.
  endmethod.

  method get_wheels.
    result = me->wheels.
  endmethod.

  method main.
    data mercedes type ref to car.
    create object mercedes.
    mercedes->set_wheels( 5 ).
    write: mercedes->get_wheels( ).
  endmethod.
endclass.

car=>main(  ).
```

**Comment by larshp** [comment]
its a bug... just haven't fixed it yet, as I guess code will typically be wrapped into a FORM or METHOD

**Comment by larshp** [comment]
try again, latest version, abaplint bug fixed and deps updated

**Comment by s7oev** [comment]
just tested with my original example + by changing the _wheels_ attribute to public and directly assigning to it, both confirmed to print correct output (5)
