### ISSUE TITLE
DO needs additional UniqueIdentifier in transpilation

### ISSUE THREAD

**Issue by joltdx** [abaplint/transpiler#204]
In order to work for scenarios like this:

![image](https://user-images.githubusercontent.com/74537631/102193218-1ad6f180-3ebc-11eb-8f25-a4c8de9bebfc.png)

Expected output:
```
1
2
3
4
```

**Comment by larshp** [comment]
heh, yea

**Comment by joltdx** [comment]
Closed by #221
