### ISSUE TITLE
Can't transpile a single file with 2 classes

### ISSUE THREAD

**Issue by esjewett** [abaplint/transpiler#24]
The following fails. Each class definition transpiles OK individually.

```ABAP
    CLASS zcl_ret DEFINITION.
      PUBLIC SECTION.
        DATA bar TYPE i.
        CLASS-METHODS
          foo
            IMPORTING
              iv_imp type string
            RETURNING
              VALUE(rv_ret) type string.
    ENDCLASS.
    CLASS zcl_ret IMPLEMENTATION.
      METHOD foo.
        rv_ret = 'X'.
      ENDMETHOD.
    ENDCLASS.
    CLASS zcl_ret2 DEFINITION.
      PUBLIC SECTION.
        DATA bar TYPE i.
        CLASS-METHODS
          blahblah
            IMPORTING
              iv_imp type string
            RETURNING
              VALUE(rv_ret) type string.
    ENDCLASS.
    CLASS zcl_ret2 IMPLEMENTATION.
      METHOD blahblah.
        rv_ret = iv_imp.
      ENDMETHOD.
    ENDCLASS.
    DATA foo TYPE REF TO zcl_ret2.
    CREATE OBJECT foo.
    WRITE foo->blahblah( iv_imp = 'Y' ).
```

**Comment by larshp** [comment]
big bug somewhere in the abaplint SpaghettiScope resolution

place cursor, click f1, wrong scope found,

![image](https://user-images.githubusercontent.com/5888506/76778323-e954bc80-67a9-11ea-91fe-758bd4ea2652.png)

**Comment by esjewett** [comment]
Yes, it finds the method of the first class :( This is why it "works" if the methods have the same name. Because it passes the `sname` check here:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/4822/76778519-fd7fc600-6777-11ea-8896-ee7322f27928.png">

It doesn't actually work, as the transpiled code is not correct, but it doesn't throw an error.

**Comment by larshp** [comment]
fixed in https://github.com/abaplint/abaplint/commit/6300fc45198fe45728d66080b89da1710a5c09d2

real fix will be with https://github.com/abaplint/abaplint/issues/808, think the transpiler can work without the real fix

I'll update the dependency, sec

**Comment by larshp** [comment]
fixed, try again

**Comment by esjewett** [comment]
@larshp I did verify that this is now working.
