### ISSUE TITLE
Operator precedence

### ISSUE THREAD

**Issue by BurnerPat** [abaplint/transpiler#28]
The following ABAP snippet:

```abap
a = a * b + c * d.
```

is transpiled to the following JavaScript code:

```javascript
a.set(a.multiply(b.add(c.multiply(d))));
```

If you set a, b, c, d to 2, 3, 4, 5, the result of the transpiled expression will be 2 * (3 + (4 * 5) = 46, due to the way the expression is constructed. The correct result would be 26.

This happens because the syntax tree abaplint creates for this expression looks like this:
![](https://user-images.githubusercontent.com/4903346/81735944-1960c900-9496-11ea-9bc2-abdc9dd48254.png)

**Comment by BurnerPat** [comment]
Other parsers like the ones generated by ANTLR resolve this problem by moving preceding operations "further down" in the syntax tree (for example: [https://github.com/antlr/grammars-v4/blob/master/arithmetic/arithmetic.g4]()).

I attempted to replicate this behavior by directly modifying the output of `getStructure()` before passing and it seemed to work: https://github.com/BurnerPat/transpiler/commit/5222318662b2307b71e7356f44fcd1e939a0a241

This changes the tree shown in the issue description to this:
![](https://user-images.githubusercontent.com/4903346/81736859-86c12980-9497-11ea-913e-e8499c2e0ebc.png)

@larshp Can you share your thoughts on this approach?

**Comment by larshp** [comment]
Its a workaround, the transpiler is a workaround as is, so its okay for now

As a long term solution, I think its possible to change the grammar so it gets the correct tree
https://syntax.abaplint.org/?filter=source#/expression/ArithOperator
but it might be a bit more work and run into other issues

**Comment by BurnerPat** [comment]
Yeah, I agree; it's definitely not a long-term solution.

I'll look into getting an MR ready for the changes and after that maybe see if I can figure something out for the grammar aswell.

**Comment by larshp** [comment]
the following two examples give different outputs, it should not
```abap
output = 100 * noun + verb.
output = ( 100 * noun ) + verb.
```

**Comment by larshp** [comment]
I guess there is the same problem with

```abap
IF 1 = 2 OR 1 = 2 AND 1 = 2.
ENDIF.
```

I would like to implement a abaplint rule which requires the precedence to be explicit, for both arithmetic and boolean, something like the second part of https://docs.abapopenchecks.org/checks/59/, the rule would have quick fixes defaulting to the default precedence

the first part of AOC59 is done in https://rules.abaplint.org/many_parenthesis/

**Comment by larshp** [comment]
https://github.com/abapGit/abapGit/blob/c554ff2fc754227dcba60d7e476f5845c94bb334/src/zcl_abapgit_version.clas.abap#L242

**Comment by larshp** [comment]
```abap
  DATA int TYPE i.
  int = 4 - 0 + 1.
  ASSERT int = 5.
```

**Comment by larshp** [comment]
@BurnerPat I tried the above fix, did not work for all my unit tests, I might do a few tweaks

```js
  it("Arithmetics, precedence 1", async () => {
    const code = `ASSERT 4 - 0 + 1 = 5.`;
    const js = await run(code);
    const f = new Function("abap", js);
    f(abap);
  });

  it("Arithmetics, precedence 2", async () => {
    const code = `
  DATA int TYPE i.
  int = 2 * 2 + 3 * 3.
  WRITE int.`;
    const js = await run(code);
    const f = new Function("abap", js);
    f(abap);
    expect(abap.console.get()).to.equal("13");
  });

  it("Arithmetics, precedence 3", async () => {
    const code = `ASSERT 100 * 10 + 2 = ( 100 * 10 ) + 2.`;
    const js = await run(code);
    const f = new Function("abap", js);
    f(abap);
  });

  it("Arithmetics, precedence 4", async () => {
    const code = `ASSERT 4 + 1 - 2 = 3.`;
    const js = await run(code);
    const f = new Function("abap", js);
    f(abap);
  });

  it("Arithmetics, precedence 5", async () => {
    const code = `ASSERT 4 + ( 1 - 2 ) = 3.`;
    const js = await run(code);
    const f = new Function("abap", js);
    f(abap);
  });

  it("Arithmetics, precedence 6", async () => {
    const code = `
  DATA int TYPE i.
  int = 4 - 1 - 2.
  WRITE int.`;
    const js = await run(code);
    const f = new Function("abap", js);
    f(abap);
    expect(abap.console.get()).to.equal("1");
  });
```

**Comment by larshp** [comment]
done, closing
