### ISSUE TITLE
integer to string conversion

### ISSUE THREAD

**Issue by larshp** [abaplint/transpiler#305]
```abap
DATA int TYPE i VALUE 2.
DATA str TYPE string.
str = int.
ASSERT str = |2 |.
```

**Comment by arcanist123** [comment]
Hi.
so you want to implement something that is described here?
https://help.sap.com/doc/abapdocu_740_index_htm/7.40/en-US/abenconversion_type_ibs.htm
[quote] The character "-" is set at the last position for a negative value, and a blank is set for a positive value. [\quote]

**Comment by joltdx** [comment]
This is no longer an issue... 😀

**Comment by larshp** [comment]
![Uploading image.png…]()
