### ISSUE TITLE
CREATE DATA

### ISSUE THREAD

**Issue by larshp** [abaplint/transpiler#385]
```abap
TYPES: BEGIN OF ty_structure,
         field TYPE string,
       END OF ty_structure.
DATA ls_data TYPE REF TO ty_structure.
CREATE DATA ls_data.
ls_data->field = 'hello'.
WRITE ls_data->field.
```

**Comment by arcanist123** [comment]
Is there a plan to support the standard classes for dynamic programming? (cl_abap_typedescr, cl_abap_structdescr and so on?)

**Comment by larshp** [comment]
the transpiler is raw transpiling, some parts of the standard system is implemented in https://github.com/open-abap/open-abap

see https://github.com/open-abap/open-abap/tree/main/src/rtti

**Comment by arcanist123** [comment]
Is it legally permitted to copy the definition of that classes? On one hand I am really interested in this project - on the other hand, I am afraid that SAP will not be very happy with it and will use legal actions in case this is becoming populate. I think this was the endresult of other projects like this one.
