### ISSUE TITLE
implement: less then and greater than for hex compared with integer values

### ISSUE THREAD

**Issue by larshp** [abaplint/transpiler#398]

**Comment by arcanist123** [comment]
I think it is a bug. The following code is producing 'lesser' currently. It should be producing greater based on original SAP compiler
``` abap
  DATA lv_hex TYPE x.
  lv_hex = '1B'.
  DATA lv_int TYPE i VALUE 4.

  IF LV_hex > lv_int.
    WRITE: 'greater'.
  ELSE.
    WRITE: 'lesser'.
  ENDIF.
```

**Comment by arcanist123** [comment]
also - does it make sense that there is separate implementations for gt and lt? they are supposedly mirrors of themselves - was there a reason why one is not implemented using another?

**Comment by larshp** [comment]
yea, I've only implemted the EQ logic for hex vs integers, https://github.com/abaplint/transpiler/blob/main/packages/runtime/src/compare/eq.ts#L56

missing is https://github.com/abaplint/transpiler/blob/main/packages/runtime/src/compare/lt.ts and https://github.com/abaplint/transpiler/blob/main/packages/runtime/src/compare/gt.ts

**Comment by arcanist123** [comment]
I assume i will check how equal works for other types also. probably there is a  bug there

**Comment by arcanist123** [comment]
this was fixed, as per my understanding. the code is giving greater now
``` abap
  DATA lv_hex TYPE x.
  lv_hex = '1B'.
  DATA lv_int TYPE i VALUE 4.

  IF lv_hex > lv_int.
    WRITE: 'greater'.
  ELSE.
    WRITE: 'lesser'.
  ENDIF.
```
