### ISSUE TITLE
Static typing is not ensured

### ISSUE THREAD

**Issue by arcanist123** [abaplint/transpiler#404]
When running the attached file, the real abap compiler is issuing a dump (as expected - the string 'ASD' cannot be interpreted as type P). The transpiler is ignoring it.
[p_type_not_protected.txt](https://github.com/abaplint/transpiler/files/6526857/p_type_not_protected.txt)

**Comment by larshp** [comment]
thanks it is a lot of work

it helps if you reduce the example, and paste it into the issue as `https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks`

in this example I guess it can be reproduced without the class, try with https://transpiler.abaplint.org

**Comment by arcanist123** [comment]
hi.

Please find the reduced example
    TYPES:
      BEGIN OF ts_test,
        a TYPE c LENGTH 4,
      END OF ts_test,
      tt_test TYPE STANDARD TABLE OF ts_test WITH DEFAULT KEY.

    DATA lt_test TYPE tt_test.
    DATA ls_test LIKE LINE OF lt_test.
    ls_test-a = 'asd'.
    APPEND ls_test TO lt_test.

    FIELD-SYMBOLS <ls> LIKE LINE OF lt_test.


    LOOP AT lt_test ASSIGNING <ls> .

      FIELD-SYMBOLS <lv> TYPE any.
      ASSIGN COMPONENT 'A' OF STRUCTURE <ls> TO <lv>.
      WRITE <lv>.

*      WRITE <ls>-a.


    ENDLOOP.

**Comment by arcanist123** [comment]
in general I dont write the code without classes. But I guess the more reduced example is, the better

**Comment by arcanist123** [comment]
```abap
data aaa type p LENGTH 10 DECIMALS 5.
aaa = 'A'.
write aaa.
```

**Comment by arcanist123** [comment]
this should dump, but it does not

**Comment by larshp** [comment]
thanks its a bug

first priority is getting correct code running, second getting the bad code running correctly ;)

**Comment by joltdx** [comment]
Resolved? Raising CX_SY_CONVERSION_NO_NUMBER now...
![image](https://github.com/user-attachments/assets/9c30ad9e-e015-4c10-96b2-48deb5ef4f60)
