### ISSUE TITLE
shift does not work in byte mode

### ISSUE THREAD

**Issue by arcanist123** [abaplint/transpiler#405]
Attached program produces the output of 06
The real compiler produces  61
assumption - such a transpilation is not correct - the xstring is not character type
lv_xstring = '0061736D' . ->lv_xstring.set(new abap.types.Character({length: 8}).set('0061736D'));

[shift_does_not_work_in_bynary_mode.txt](https://github.com/abaplint/transpiler/files/6526880/shift_does_not_work_in_bynary_mode.txt)

**Comment by arcanist123** [comment]
reduced example
``` abap
    DATA lv_xstring TYPE xstring.
    lv_xstring = '0061736D' .
    SHIFT lv_xstring IN BYTE MODE BY 1 PLACES CIRCULAR.
    WRITE: lv_xstring+0(1).
```

**Comment by larshp** [comment]
SHIFT runtime = https://github.com/abaplint/transpiler/blob/main/packages/runtime/src/statements/shift.ts
SHIFT transpiler = https://github.com/abaplint/transpiler/blob/main/packages/transpiler/src/statements/shift.ts
SHIFT unit tests = https://github.com/abaplint/transpiler/blob/main/test/statements/shift.ts
