### ISSUE TITLE
rounding is applied incorrectly

### ISSUE THREAD

**Issue by arcanist123** [abaplint/transpiler#407]
Rounding for type P is not working properly. I wonder if type P was at all implemented or is it internally I
the code below produces 100 ten times. it should produce the following numbers instead.
 100,999       101,998       102,997       103,996       104,995       105,994       106,993       107,992       108,991       109,990
``` abap

    DATA lv_test TYPE p LENGTH 6 DECIMALS 3.
    lv_test = 100.

    DO 10 TIMES.
      lv_test = lv_test / 3.
      lv_test = lv_test * 3.
      lv_test = lv_test + 1.
      WRITE lv_test.
    ENDDO.
```

**Comment by larshp** [comment]
yea, packed still needs some work

thanks for the bug report

**Comment by joltdx** [comment]
Seems to be resolved
![image](https://github.com/user-attachments/assets/79f4eaed-070e-4513-bf54-f2a3919005c5)
