### ISSUE TITLE
Statement Unassign not supported, unassign <field>

### ISSUE THREAD

**Issue by sbcgua** [abaplint/transpiler#539]

**Comment by larshp** [comment]
the statement as such seems to work, however the field symbol is not checked for existence,

![image](https://user-images.githubusercontent.com/5888506/137247265-4dbf01f8-f204-40d0-bc8b-ce0749f423a1.png)

![image](https://user-images.githubusercontent.com/5888506/137247281-9f5823b9-5ad1-4c97-94e5-b140933453a0.png)

**Comment by larshp** [comment]
@sbcgua try againn, 1.6.47
