### ISSUE TITLE
OR upper/lower case?

### ISSUE THREAD

**Issue by larshp** [abaplint/transpiler#543]
first part not working, second part working

@sbcgua this might be a good first issue if you like? if not I'll look into it tomorrow

ref https://github.com/sbcgua/text2tab/pull/23

```abap
data i_amount_format type c length 2.
if not ( i_amount_format is initial or i_amount_format+1(1) is initial ).
endif.

DATA i_amount_format TYPE c LENGTH 2.
IF NOT ( i_amount_format IS INITIAL OR i_amount_format+1(1) IS INITIAL ).
ENDIF.
```

**Comment by sbcgua** [comment]
yeah, I don't mind but I need some routing ... and ideally some unit testing guidance ... and dev flow ... 
I guess this is a part of `cond.ts` or `component_cond.ts` but not sure how to practically check it. The downside of missing docs :)
