### ISSUE TITLE
String conversion of float

### ISSUE THREAD

**Issue by mbtools** [abaplint/transpiler#678]
```abap
data f type f.
data out type string.
f = '10.239'.
out = |f = { f }|.
write / out.
out = |f = { f decimals = 2 }|.
write / out.
```

output: 
`f = 1,2390000000000000E+01`
`f = 1,2390000000000000E+01`

expected:
`f = 10.2390000000000001`  10.239 should be ok too since floats are platform dependent
`f = 10.24`

Note: you get `E+xx` in ABAP if you use `exponent = n` in the template (for n <> 0).

**Comment by larshp** [comment]
related, but not identical = https://github.com/abaplint/transpiler/issues/673

**Comment by larshp** [comment]
@mbtools try again, 2.2.18

**Comment by mbtools** [comment]
👍
