### ISSUE TITLE
Error combining string template formatting options

### ISSUE THREAD

**Issue by pokrakam** [abaplint/transpiler#683]
String template formatting options cannot be combined, syntax error.
Causes https://github.com/exercism/abap/issues/102

Paste into https://transpiler.abaplint.org and uncomment line to reproduce:
```abap
data h type i value 2.
data m type i value 5.
write / |{ h WIDTH = 2 }:{ m PAD = '0' }|.
"write / |{ h WIDTH = 2 PAD = '0' }:{ m }|.
```

**Comment by larshp** [comment]
#684

**Comment by larshp** [comment]
@pokrakam try again

**Comment by larshp** [comment]
this fails,

`    result = |{ ls_time-hours PAD = '0' WIDTH = 2 ALIGN = RIGHT }:{ ls_time-minutes PAD = '0' WIDTH = 2 ALIGN = RIGHT }|.`

**Comment by larshp** [comment]
reduced to below, expect output "02:02"

```abap
DATA result TYPE string.
DATA hours TYPE i.
DATA minutes TYPE i.
hours = 2.
minutes = 2.
result = |{ hours PAD = '0' WIDTH = 2 ALIGN = RIGHT }:{ minutes PAD = '0' WIDTH = 2 ALIGN = RIGHT }|.
WRITE result.
```

**Comment by larshp** [comment]
@pokrakam try again, latest version

**Comment by larshp** [comment]
closing, no reply
