### ISSUE TITLE
Set sy-datum, uzeit, etc

### ISSUE THREAD

**Issue by mbtools** [abaplint/transpiler#690]
It was mentioned in comments of https://blogs.sap.com/2022/03/30/abap-on-exercism/

```abap
write sy-datum.
 = 00000000
```

https://github.com/abaplint/transpiler/blob/main/packages/runtime/src/builtin/sy.ts

The following should not be initial...
`sy-datum, sy-uzeit, sy-datlo, sy-timlo`

Set `sy-tzone` to `0` which is the value for `UTC`.

**Comment by larshp** [comment]
@mbtools try again, latest version

**Comment by mbtools** [comment]
Looks in sync now (my PC is at UTC+2)

![image](https://user-images.githubusercontent.com/59966492/166141799-b1fe3485-d83d-4c8e-9ab9-dbf6740f5804.png)
