### ISSUE TITLE
Incorrect MOD implementation

### ISSUE THREAD

**Issue by pokrakam** [abaplint/transpiler#692]
ABAP and SQL MOD behave different. Transpiler should use the ABAP logic of positive modulo.

```abap
data n type i.

n = 4 mod 3.
write / n.

n = -4 mod 3.
write / n.
```

Transpiler output is  `1` `-1` and ABAP output is `1` `2`.
Resolves https://github.com/exercism/abap/issues/121

**Comment by larshp** [comment]
😁

**Comment by bizhuka** [comment]
the solution could be like that

``` abap
" in JS instead of
rv_mod  = lv_number mod unit.

" a little longer
rv_mod = ( ( lv_number mod unit ) + unit ) mod unit.
```

**Comment by larshp** [comment]
wonder what the ABAP documentation says,

![image](https://user-images.githubusercontent.com/5888506/161488465-0bec73d6-5316-4171-ac66-04d8f0c10575.png)

**Comment by bizhuka** [comment]
<html>
<body>


MOD | Positive remainder of the division of the left operand by the right; a remainder other than zero is always between zero and the size of the right operand
-- | --



</body>
</html>

**Comment by larshp** [comment]
https://stackoverflow.com/questions/4467539/javascript-modulo-gives-a-negative-result-for-negative-numbers

**Comment by pokrakam** [comment]
The doc says both, depends on whether you're working on [ABAP-SQL MOD](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abensql_functions_numeric.htm) or [ABAP-ABAP MOD](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/index.htm?file=abenarith_operators.htm) - see examples.

Every language is different, see [Wikipedia](https://en.wikipedia.org/wiki/Modulo_operation)

**Comment by larshp** [comment]
@pokrakam try again, latest version

**Comment by pokrakam** [comment]
Looks good 👍
