### ISSUE TITLE
Shift_left needs to handle optional input places and circular

### ISSUE THREAD

**Issue by Dwivedirahul44** [abaplint/transpiler#714]
Code path packages/runtime/src/builtin/shift_left.ts
add **places** and **circular** parameters to shift_left function
As of now only **val** and **sub** are supported
```  JavaScript
export function shift_left(input: {val: ICharacter | string, sub: ICharacter | string}): ICharacter

**Comment by larshp** [comment]
thanks, yea, its a bug
