### ISSUE TITLE
add builtin function `to_mixed`

### ISSUE THREAD

**Issue by Dwivedirahul44** [abaplint/transpiler#715]
/transpiler/packages/runtime/src)/builtin/
Requesting addition of built-in case function to_mixed with parameters: 
 val type string
sep type string optional
case type string optional
min type I  optional

**Comment by larshp** [comment]
some test cases, I'm not really sure what `min` does, is it required for now?

```abap
DATA m TYPE string.
m = to_mixed( val  = |Hello World| ).
ASSERT m = 'Hello world'.
m = to_mixed( val  = |Hello_World| ).
ASSERT m = 'HelloWorld'.
m = to_mixed( val  = |Hello World| sep  = | | ).
ASSERT m = 'HelloWorld'.
m = to_mixed( val  = |Hello World| sep  = | | case = 'a' ).
ASSERT m = 'helloWorld'.
m = to_mixed( val  = |Hello World| sep  = | | case = 'A' ).
ASSERT m = 'HelloWorld'.
```

**Comment by Dwivedirahul44** [comment]
Min is an advanced option for separator and case manipulation. it represents how many characters before the separator is considered. the default value for min is 1. 
```ABAP
ASSERT |HelloTo world| = to_mixed( val  = |Hello to world| sep  = | | case = 'A' min = 3 ).
ASSERT |HelloToWorld| =  to_mixed( val  = |Hello to world| sep  = | | case = 'A' ).
```
we can leave it for now.

**Comment by larshp** [comment]
@Dwivedirahul44 try again, latest version

**Comment by Dwivedirahul44** [comment]
@larshp - I tested it and it looks good for all except **min** input values are being ignored( internally hardcoded to 1).
Maybe not have **min** as an input to avoid confusion, otherwise, we can close the bug.

**Comment by larshp** [comment]
pull requests welcome :)

**Comment by Dwivedirahul44** [comment]
Closing the issue.
