### ISSUE TITLE
`replace` needs to handle abap regex character classes 

### ISSUE THREAD

**Issue by Dwivedirahul44** [abaplint/transpiler#716]
Using ABAP character classes like **[:punct:]**(  all punctuations ) in regex doesn't seem to be returning the desired result.

Link to the reported issue.
[https://github.com/exercism/abap/issues/142#issue-1206127130](url)

**Comment by larshp** [comment]
reproduced as

```abap
DATA plain_text TYPE string.
DATA result TYPE string.
plain_text = |hello, world.moo|.
result = replace( val = plain_text regex = '[[:punct:]]' with = ' ' occ = 0 ).
WRITE result.
```

expected value = "hello worldmoo"

**Comment by larshp** [comment]
@Dwivedirahul44 try again

**Comment by Dwivedirahul44** [comment]
@larshp - Thanks for adding the changes, I tested and it works well with commas and period. 
However, I request you to add a full set of punctuation class characters to truly represent ABAP behaviour.
I tried to add as much as I could( abap documentation is not much help).
Reproduced as 
```ABAP
data(result) = replace( val = 'H-{}[...]ello,Wo:,rld!?.();''' regex = '[[:punct:]]' with = ' ' occ = 0 ).
write result.
result = replace( val = 'H-{}[...]ello,Wo:,rld!?.();''' regex = '[\.\,\-\{\}\[\]\:\!\?\(\)\;\'']' with = ' ' occ = 0 ).
write result.
```
I am not that good at typescript but I think replacing code at **src/abap_regex.ts** might help.
```typescript
//oldcode
ret = input.replace(/\[\[:punct:\]\]/g, "[\\.\\,]");
// new code
ret = input.replace(/\\[\\[:punct:\\]\\]/g, "[\\.\\,\\-\\{\\}\\[\\]\\:\\!\\?\\(\\)\\;\\']");
```
if you are planning to club this with later releases, we can close this bug.

**Comment by Dwivedirahul44** [comment]
Closing the bug.
