### ISSUE TITLE
downport ASSIGN lt_table[ index ] to READ TABLE lt_table INDEX index

### ISSUE THREAD

**Issue by bizhuka** [abaplint/transpiler#730]
Hello
It looks like downport of **ASSIGN lt_table[ ind ]** to **READ TABLE lt_table INDEX ind** doesn't work

May be it's better to enlist the issue in abap downport or exercism's github
https://exercism.org/tracks/abap/exercises/matrix/iterations

``` abap
CLASS zcl_matrix DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES integertab TYPE STANDARD TABLE OF i WITH EMPTY KEY.
    METHODS matrix_row
      IMPORTING
        string        TYPE string
        index         TYPE i
      RETURNING
        VALUE(result) TYPE integertab.
    METHODS matrix_column
      IMPORTING
        string        TYPE string
        index         TYPE i
      RETURNING
        VALUE(result) TYPE integertab.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS zcl_matrix IMPLEMENTATION.
  METHOD matrix_row.
    SPLIT string AT '\n' INTO TABLE DATA(lt_rows).

    ASSIGN lt_rows[ index ] TO FIELD-SYMBOL(<lv_row>).
    CHECK sy-subrc = 0.

    SPLIT <lv_row> AT space INTO TABLE DATA(lt_row).
    result = VALUE #( FOR lv_val IN lt_row ( CONV #( lv_val ) ) ).
  ENDMETHOD.

  METHOD matrix_column.
    SPLIT string AT '\n' INTO TABLE DATA(lt_rows).

    LOOP AT lt_rows ASSIGNING FIELD-SYMBOL(<lv_row>).
      DATA(lt_row) = matrix_row( string = <lv_row>
                                 index  = 1 ).

      " ---> ASSIGN lt_row[ index ] TO FIELD-SYMBOL(<lv_val>).
      READ TABLE lt_row INDEX index ASSIGNING FIELD-SYMBOL(<lv_val>).   
      CHECK sy-subrc = 0.
      APPEND <lv_val> TO result.
    ENDLOOP.
  ENDMETHOD.
ENDCLASS.
```

**Comment by bizhuka** [comment]
the issue is very strange since here **ASSIGN lt_rows[ index ]** works pretty well

``` abap
CLASS zcl_matrix IMPLEMENTATION.
  METHOD matrix_row.
    SPLIT string AT '\n' INTO TABLE DATA(lt_rows).

    ASSIGN lt_rows[ index ] TO FIELD-SYMBOL(<lv_row>).
    CHECK sy-subrc = 0.
```

**Comment by bizhuka** [comment]
it could be caused by the case that **ASSIGN** do not change **sy-subrc**

**Comment by larshp** [comment]
clone https://github.com/larshp/exercism-test, put the code into the `src` folder, run `npm install` and `npm test`

then its possible to debug and check the code after each step, check folders `downport` and `output`

**Comment by bizhuka** [comment]
downported version raises **cx_sy_itab_line_not_found**
``` abap
      READ TABLE lt_row INDEX index INTO temp5.
      sy-tabix = temp6.
      IF sy-subrc <> 0.
        RAISE EXCEPTION TYPE cx_sy_itab_line_not_found.
      ENDIF.
```

**Comment by bizhuka** [comment]
Hi
finally imho figured out the cause of the error

---
**table_exp - Table Expressions**
https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abentable_expressions.htm

* Unlike **READ TABLE**, a table expression does not modify the value of the system field sy-tabix.
in downported code *sy-tabix = temp6.*

* If the specified row is not found, a handleable expression of the class **CX_SY_ITAB_LINE_NOT_FOUND** is raised in all operand positions

---

**ASSIGN tab[]** in another hand
https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abapassign.htm

* do not cause CX_SY_ITAB_LINE_NOT_FOUND exception
* and change **sy-tabix**

---

found the same error here
https://exercism.org/tracks/abap/exercises/itab-basics/solutions/bizhuka
line 67
``` abap
    ASSIGN temp_data[ number = 6 ] TO FIELD-SYMBOL(<ls_result>).
```
transpiled to ordinary **Table Expressions** without changing sy-tabix and with CX_SY_ITAB_LINE_NOT_FOUND

``` abap
    temp2 = sy-tabix.
    READ TABLE temp_data WITH KEY number = 6 INTO temp1.
    sy-tabix = temp2.
    IF sy-subrc <> 0.
      RAISE EXCEPTION TYPE cx_sy_itab_line_not_found.
    ENDIF.
    ASSIGN temp1 TO <ls_result>.
    CHECK <ls_result> IS ASSIGNED.
```

**Comment by larshp** [comment]
note https://github.com/abaplint/abaplint/commit/516349f40e332e196d3765db9aaf8d726e38db15#diff-ada635ed0af76e0fa61efaf5cef98f0808f198f96d12252aee29f728354f0d56 was fixed a few days ago

**Comment by larshp** [comment]
need a minimal example to reproduce and fix, and only one scenario at a time

the issue starts with by index, `ASSIGN lt_rows[ index ] TO FIELD-SYMBOL(<lv_row>).`, but examples are moving into by component compare `ASSIGN temp_data[ number = 6 ] TO FIELD-SYMBOL(<ls_result>).`

**Comment by larshp** [comment]
seems to work?

```abap
DATA tab TYPE STANDARD TABLE OF i WITH DEFAULT KEY.
FIELD-SYMBOLS <fs> TYPE any.
ASSIGN tab[ 1 ] TO <fs>.
WRITE sy-subrc.
WRITE sy-tabix.
```

downports to

```abap
DATA tab TYPE STANDARD TABLE OF i WITH DEFAULT KEY.
FIELD-SYMBOLS <fs> TYPE any.
READ TABLE tab INDEX 1 ASSIGNING <fs>.
WRITE sy-subrc.
WRITE sy-tabix.
```

**Comment by bizhuka** [comment]
updated the github repo & checked in exercism again
the error is present

![image](https://user-images.githubusercontent.com/36256417/184617189-92681368-c7a4-435d-b149-2eab2a076aef.png)

[code.zip](https://github.com/abaplint/transpiler/files/9336548/code.zip)

**Comment by larshp** [comment]
in the first comment the example code contains `ASSIGN lt_rows[ index ] TO FIELD-SYMBOL(<lv_row>).`, which is not what you have in the screenshot above. Its difficult for me if the example changes through the issue, also note that my comment is `ASSIGN tab[ index ]`

also see comment in https://github.com/abaplint/transpiler/issues/730#issuecomment-1214843282

**Comment by bizhuka** [comment]
sorry for the inconvenience
just saw the same error in new exercise
https://exercism.org/tracks/abap/exercises/itab-basics
& decide to write in this issue


---
here
https://github.com/larshp/exercism-test/blob/b168a2e37d6481a26657d842d0e921f15e3201d8/package.json#L20

have changed
    "@abaplint/cli": "^2.91.**28"**,
to new version
    "@abaplint/cli": "^2.91.**29**",
and then the code downported properly :+1:

---
it seems to me that [https://exercism.org/](https://exercism.org/) also uses abaplint/cli": "^2.91.**28"**

thank you
sorry the confusing description

**Comment by larshp** [comment]
the exercism test runner is updated every now and then

anyhow, another downport rule regarding ASSIGN by component added in https://github.com/abaplint/abaplint/pull/2644
