### ISSUE TITLE
SQL: Join condition wrongly detected as where condition

### ISSUE THREAD

**Issue by thorsten-wolf-neptune** [abaplint/transpiler#741]
When a SQL Statement uses a JOIN Statement (ON ...) and a WHERE Statement. The ON ... expression is treated as WHERE Expression.
![image](https://user-images.githubusercontent.com/83953375/170695778-2d5af84d-b3c5-4b01-93c5-706f1394c619.png)
https://github.com/abaplint/transpiler/blob/f0f6d559a02d930896612b2de8d6459f65d39c2d/packages/transpiler/src/statements/select.ts#L16

**Comment by larshp** [comment]
closing
