### ISSUE TITLE
database_setup, todo toType handle: DateType

### ISSUE THREAD

**Issue by Zeatynis** [abaplint/transpiler#765]
When this occurs what does it mean? 
Should there be a type conversion implemented for the Data type?

I've extended the error to show the object's name at which it occured (https://github.com/abaplint/transpiler/pull/764) 
And I am 100% sure that within my libs there is the domain that this objects uses.

**Comment by Zeatynis** [comment]
@larshp ?

**Comment by larshp** [comment]
I receive everything, just 100s of them, so I do heavy sorting/prioritization

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/766

**Comment by Zeatynis** [comment]
> I receive everything, just 100s of them, so I do heavy sorting/prioritization, plus I also need to work on paying the rent

I can imagine. Sorry, I didn't mean to rush you. I got used to your unreally fast responses and wasn't sure if you've seen this 😄

**Comment by Zeatynis** [comment]
I tested #766 and it seems that the issue is gone 👍
