### ISSUE TITLE
web: Initial code 

### ISSUE THREAD

**Issue by mbtools** [abaplint/transpiler#872]
Instead of a hardcoded "WRITE 'hello'." can we get the initial code from another source?
https://github.com/abaplint/transpiler/blob/main/web/transpiler/src/index.ts#L28

Either could work:
- '.abap' file (not packed so it can be edited in the web repo)
- function in a '.js' to return the code (not packed so it can be edited in the web repo)
- URL

Just adds some flexibility on how we could start it up (in my fork ;-) ).

**Comment by larshp** [comment]
hmm, well, I think feel free to change the hardcoded value to whatever

but I guess you need something more/different?

**Comment by mbtools** [comment]
yes, something longer like https://github.com/hdegroot/zwordle/blob/9cd0d005d7de5dacccd242e4d68268eee7ab4573/transpiler/zwordle.abap

eventually, I could hide the editor controls and have an ABAP app on the web

**Comment by mbtools** [comment]
https://wordle.marcbernardtools.com/
https://github.com/Marc-Bernard-Tools/Wordle-Assistant
https://twitter.com/marcfbe/status/1579932361302548480
