### ISSUE TITLE
Select with `LIKE` and `ESCAPE`

### ISSUE THREAD

**Issue by mbtools** [abaplint/transpiler#902]
https://github.com/abapGit/abapGit/pull/5786

https://github.com/abapGit/abapGit/actions/runs/3161406748/jobs/5146956094

```abap
SELECT * FROM dokil INTO TABLE lt_dokil WHERE object LIKE lv_object ESCAPE '#'.
```

**Comment by larshp** [comment]
@mbtools updated, try again

**Comment by mbtools** [comment]
👍
