### ISSUE TITLE
Assignment type p to i does not round

### ISSUE THREAD

**Issue by mbtools** [abaplint/transpiler#968]
```abap
DATA i TYPE i.
i = sqrt( 50 ).
WRITE i.
i = sqrt( 58 ).
WRITE i.
```

or

```abap
DATA(i) = CONV i( sqrt( 50 ) ).
```

expected: 7 and 8
actual: 7.0710678118654755 and 7.61577310586390

https://help.sap.com/doc/abapdocu_756_index_htm/7.56/en-US/index.htm?file=abenconversion_type_p.htm

**Comment by larshp** [comment]
@mbtools try again

**Comment by mbtools** [comment]
👍
