### ISSUE TITLE
`round` does not work properly

### ISSUE THREAD

**Issue by mbtools** [abaplint/transpiler#970]
```abap
DATA p TYPE p LENGTH 10 DECIMALS 2.
p = round( val = '7.1' dec = 0 ).
WRITE / p.
p = round( val = '7.6' dec = 0 ).
WRITE / p.
```

actual: 8.00 and 8.00

https://help.sap.com/doc/abapdocu_756_index_htm/7.56/en-US/index.htm?file=abendec_floating_point_functions.htm

From `cl_abap_math`. The default is `mode = 2` (yeah)

```abap
constants ROUND_HALF_UP   type I value 2. "Round away from zero if value is exactly half
constants ROUND_HALF_DOWN type I value 4. "Round to zero if value is exactly half
constants ROUND_HALF_EVEN type I value 3. "Round so last digit is an even no. if value is exactly half
constants ROUND_UP        type I value 1. "Round away from zero
constants ROUND_DOWN      type I value 5. "Round to Zero
constants ROUND_CEILING   type I value 0. "Round to Positive Infinity
constants ROUND_FLOOR     type I value 6. "Round to Negative Infinity
```

https://github.com/abaplint/transpiler/blob/83bf10d863aea0ca668e0224f2ba72606bbc7fd5/packages/runtime/src/builtin/round.ts#L9-L10

https://github.com/abaplint/transpiler/blob/83bf10d863aea0ca668e0224f2ba72606bbc7fd5/packages/runtime/src/builtin/round.ts#L22-L31

I think it should be as follows:
```
mode = 0: Math.ceil
mode = 1: if x < 0. Math.floor. else Math.ceil
mode = 2: Math.round
mode = 5: Math.trunc
mode = 6: Math.floor
```

Not sure how we do mode 3 and 4. well `todo`

This prg shows all combinations: 
https://gist.github.com/mbtools/b40dddb96d7316c606118871ef5ee50e

**Comment by larshp** [comment]
@mbtools try again

**Comment by mbtools** [comment]
👍
